version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./certs:/certs

    environment:
      - API_URL=https://api:8000
      - CLIENT_CERT=/certs/client-cert.pem
      - CLIENT_KEY=/certs/client-key.pem
      - CA_CERT=/certs/ca-cert.pem
    networks:
      - external-network

networks:
  external-network:
    external: true
