version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - API_URL=http://api:8000
    networks:
      - external-network

networks:
  external-network:
    external: true
